# Generated by Django 2.0.2 on 2018-03-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20180322_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.UUIDField(default='464feb1038a44ec3823f4ac0721d4698', editable=False, primary_key=True, serialize=False),
        ),
    ]
