# Generated by Django 2.0.2 on 2018-03-26 18:42

import app.classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20180327_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default=app.classroom.models.generate_code, max_length=7),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.UUIDField(default='d76016931eea45fc80aecc6255835df1', editable=False, primary_key=True, serialize=False),
        ),
    ]
