# Generated by Django 2.0.2 on 2018-03-26 18:47

import app.classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20180327_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.UUIDField(default=app.classroom.models.hex_uid, editable=False, primary_key=True, serialize=False),
        ),
    ]
