# Generated by Django 2.0.2 on 2018-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20180327_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.TextField(default='adaknaskjvnakjvnkjsgnkjgnkjsgnkjsgnkjsgnkjsdgnksjgnskgjn'),
        ),
    ]
