# Generated by Django 2.0.2 on 2018-03-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180313_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(default='images/profile_default.jpg', upload_to='profile'),
        ),
    ]
