# Generated by Django 2.0.2 on 2018-03-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180327_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default='a189b8664c024b35a9d1cd06c5887228', editable=False, primary_key=True, serialize=False),
        ),
    ]
