# Generated by Django 2.0.2 on 2018-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180327_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default='90f3f23323ee4c5ead78026ebaa785b9', editable=False, primary_key=True, serialize=False),
        ),
    ]
